### ISSUE TITLE
It repeteadly disconnects

### ISSUE THREAD

**Issue by BayramInanc** [appwoodpecker/woodpecker-client#1]
Hi, 
I am using latest macos client version and ios sdk version. However, every 15-30 seconds, Macos-client disconnects from app.

**Comment by github-xiaogang** [comment]
@BayramInanc  Hi,
1. Please provide the Mac version number and iOS framework version number 
    - Woodpecker(latest 1.4.1)
    - iOS framework(latest 1.4.0)
2. It is normal for the app to be disconnected when it enters the background or locks the screen. It will automatically resume when the app reopened.
3. The problem may be caused by certain operations. I hope you could provide more information to help reproduce the problem.

**Comment by BayramInanc** [comment]
ios version : 16.6.1 ,
mac version 1.4.0(in App store)
ios framework 1.4.0

App does not enter background operation or something like that, suddenly after 15-30 seconds disconnection happens

**Comment by github-xiaogang** [comment]
okay,  please try the release version in this repo(1.4.1), it includes some bug fixes.

**Comment by BayramInanc** [comment]
Thank you I tried and noticed if I run again in XCode then disconnection happens.  Otherwise, connection persists
